// frontend-angular/react-reference/components/Footer.jsx
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Car } from "lucide-react";
import LanguageSwitcher from "@/components/LanguageSwitcher";

const Footer = () => {
  const { t } = useTranslation();

  return (
    <footer className="bg-foreground text-background py-12 px-4">
      <div className="max-w-7xl mx-auto">
        <div className="grid md:grid-cols-4 gap-8">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-10 h-10 rounded-full bg-primary flex items-center justify-center">
                <Car className="w-6 h-6 text-primary-foreground" />
              </div>
              <span className="text-xl font-bold font-['Outfit']">AxisRide</span>
            </div>
            <p className="text-background/60 text-sm">{t("common.tagline")}</p>
            <div className="mt-4">
              <LanguageSwitcher variant="footer" />
            </div>
          </div>
          <div>
            <h4 className="font-semibold mb-4">{t("common.product")}</h4>
            <ul className="space-y-2 text-background/60 text-sm">
              <li><Link to="/#features" className="hover:text-background">{t("common.features")}</Link></li>
              <li><Link to="/pricing" className="hover:text-background">{t("common.pricing")}</Link></li>
              <li><Link to="/subscription" className="hover:text-background">{t("common.subscription")}</Link></li>
              <li><Link to="/mobile-app" className="hover:text-background">{t("common.mobileApp")}</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold mb-4">{t("common.company")}</h4>
            <ul className="space-y-2 text-background/60 text-sm">
              <li><Link to="/about" className="hover:text-background">{t("common.about")}</Link></li>
              <li><Link to="/careers" className="hover:text-background">{t("common.careers")}</Link></li>
              <li><Link to="/contact" className="hover:text-background">{t("common.contact")}</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold mb-4">{t("common.legal")}</h4>
            <ul className="space-y-2 text-background/60 text-sm">
              <li><Link to="/terms" className="hover:text-background">{t("common.terms")}</Link></li>
              <li><Link to="/privacy" className="hover:text-background">{t("common.privacy")}</Link></li>
              <li><Link to="/cookies" className="hover:text-background">{t("common.cookies")}</Link></li>
            </ul>
          </div>
        </div>
        <div className="border-t border-background/10 mt-12 pt-8 text-center text-background/40 text-sm">
          {t("common.copyright")}
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// frontend-angular/src/app/core/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { LanguageSwitcherComponent } from '../../../components/language-switcher/language-switcher.component';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, TranslateModule, RouterModule],
  templateUrl: './footer.component.html'
})
export class FooterComponent {
  readonly LanguageSwitcherComponent = LanguageSwitcherComponent;
}

<footer class="bg-foreground text-background py-12 px-4">
  <div class="max-w-7xl mx-auto">
    <div class="grid md:grid-cols-4 gap-8">
      <div>
        <div class="flex items-center gap-2 mb-4">
          <div class="w-10 h-10 rounded-full bg-primary flex items-center justify-center">
            <svg class="w-6 h-6 text-primary-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3 13l2-5h14l2 5M5 13h14M5 13v5a1 1 0 001 1h1a1 1 0 001-1v-1h8v1a1 1 0 001 1h1a1 1 0 001-1v-5M7 13V9m10 4V9" />
            </svg>
          </div>
          <span class="text-xl font-bold font-['Outfit']">AxisRide</span>
        </div>
        <p class="text-background/60 text-sm">
          {{ 'common.tagline' | translate }}
        </p>
        <div class="mt-4">
          <ng-container *ngComponentOutlet="LanguageSwitcherComponent"></ng-container>
        </div>
      </div>
      <div>
        <h4 class="font-semibold mb-4">{{ 'common.product' | translate }}</h4>
        <ul class="space-y-2 text-background/60 text-sm">
          <li><a href="#features" class="hover:text-background">{{ 'common.features' | translate }}</a></li>
          <li><a routerLink="/pricing" class="hover:text-background">{{ 'common.pricing' | translate }}</a></li>
          <li><a routerLink="/mobile-app" class="hover:text-background">{{ 'common.mobileApp' | translate }}</a></li>
        </ul>
      </div>
      <div>
        <h4 class="font-semibold mb-4">{{ 'common.company' | translate }}</h4>
        <ul class="space-y-2 text-background/60 text-sm">
          <li><a routerLink="/about" class="hover:text-background">{{ 'common.about' | translate }}</a></li>
          <li><a routerLink="/careers" class="hover:text-background">{{ 'common.careers' | translate }}</a></li>
          <li><a routerLink="/contact" class="hover:text-background">{{ 'common.contact' | translate }}</a></li>
        </ul>
      </div>
      <div>
        <h4 class="font-semibold mb-4">{{ 'common.legal' | translate }}</h4>
        <ul class="space-y-2 text-background/60 text-sm">
          <li><a routerLink="/terms" class="hover:text-background">{{ 'common.terms' | translate }}</a></li>
          <li><a routerLink="/privacy" class="hover:text-background">{{ 'common.privacy' | translate }}</a></li>
          <li><a routerLink="/cookies" class="hover:text-background">{{ 'common.cookies' | translate }}</a></li>
        </ul>
      </div>
    </div>
    <div class="border-t border-background/10 mt-12 pt-8 text-center text-background/40 text-sm">
      {{ 'common.copyright' | translate }}
    </div>
  </div>
</footer>
